# User-relevant parameters
num_stacks: 50               # number of image stacks to be generated
real_bogus_ratio: 0.5          # the ratio of stacks with asteroids: stack without asteroids
num_frames: 32                 # number of frames in each image stack
observer: '500'                # the observer location according to MPC codes
output_image_width: 224        # in pixels
output_image_height: 224
dt: 30                         # the single frame exposure time (seconds)
slew_time: 2                   # time between exposures
sig_rn: 1.6                    # the read noise specification of the telescope in electrons per pixel
i_dark: 0.5                    # the dark current specification of the telescope in electrons per second pixel
v_bg: 20.5                     # the background sky brightness for the telescope in magnitude per arcsec^2
v_0: 22.1                      # the telescope's system zero point in magnitudes
pixel_scale: 1.26              # the pixel scale of the telescope in arcsec per pixel
classes: ['Asteroid Present', 'Not']    # classes to be determined from stacks
class_labels: [True, False]
train_val_ratio: 0.5                    # ratio of samples in training set versus validation set, the test set is generated apart

# if you change of the sub file's column names, then you have to adjust the master file column names as well
master_file_name: 'sample_master_'                                       # the base name of the master file containing all statistics on all images generated
distribution_file_name: 'NEA_distributions_'                             # the base name of the file containing stats on the synthetic NEAs
snr_file_name: 'snr_stats_'                                              # the base name of the file containing stats on the expected snr and signal of synth. NEAs
center_file_name: 'asteroid_centers_'                                    # the centers where the asteroid is implanted in the first frame
stack_file_name: 'stack_stats_'                                          # the base name of the file containing stats on the image backgrounds
sbd_file_name: 'NEA_database_ssb.csv'                                    # database of current NEAs downloaded from JPL site
horizons_file_name: 'NEA_database_hor.csv'                               # queried asteroids from the sbd file, for elements that are needed
real_image_directory: 'synthetic_tracklets/real_image_stacks'            # the directory where background images should be taken
#synthetic_image_directory: 'synthetic_tracklets/synthetic_image_stacks'  # where cropped backgrounds should be stored
synthetic_image_directory: '/media/aeromec/Seagate Desktop Drive/asteroid_data'
test_set_directory: '/media/aeromec/Seagate Desktop Drive/asteroid_data/test3'                           # where the test files are located to see if the generator is performing correctly


# column names of various files that are generated and read
master_file_columns: [ 'H', 'omega', 'obs. ast. dist.', 'sun. ast. dist.', 'phase angle', 'Theta',
                       'Sigma_g', 'g_12', 'Asteroid Present', 'Expected SNR', 'Expected Signal', 'Original Image', 'Saved as Stack', 'Stack Mean',
                       'Stack Median', 'Stack Standard Deviation', 'Stack Crop Start', 'Center x', 'Center y' ]
distribution_file_columns: [ 'H', 'omega', 'obs. ast. dist.', 'sun. ast. dist.', 'phase angle', 'Theta', 'Sigma_g', 'g_12', 'Asteroid Present']
stack_file_columns: [ 'Original Image', 'Saved as Stack', 'Stack Mean', 'Stack Median', 'Stack Standard Deviation',
                      'Stack Crop Start']
snr_file_columns: [ 'Expected SNR', 'Expected Signal' ]
center_file_columns: [ 'Center x', 'Center y' ]

# Specific to DistribuGen object, creating samples from known asteroid distributions #################################
sbd_file_columns: [ 'full_name', 'a', 'e', 'i', 'om', 'w', 'q', 'ad', 'per_y',
                    'data_arc', 'n_obs_used', 'H', 'first_obs', 'epoch' ]  # the column names of the sbd file
horizons_file_columns: [ 'full_name', 'a', 'e', 'i', 'om', 'w', 'q', 'ad', 'per_y', 'data_arc', 'n_obs_used',
                         'H', 'first_obs', 'epoch', 'omega', 'obs. ast. dist.', 'sun. ast. dist.',
                         'phase angle' ]  # add columns to the sdb file according to necessary queries

# The default option is 's' for standard, checks all distributions for fitting, does visualization, and generates
# samples. The 'q' parameter is for quick, only fitting against common distributions, the 'v' parameter is for
# visualization, where if 'v' is specified, visualizations are NOT included. If 'm' is specified, then samples are
# NOT generated. The 'q', 'm' and 'v' parameters can be specified in combinations but the exact results for each
# combination is not verified. 't' is for using the test set file, 't2' is for second version of testset
options: 'qv'

# For some distributions, like the apparent motion, there may be some range over which you want the distribution to be
# fitted, as there may be some outlier data from JPL Horizons. It is specified as a list of lists: [[min parameter 1,
# max parameter 1], ..., [min parameter n, max parameter n]]. If not specified it will use the entire range (except for
# apparent motion, where it cuts off at around 100 deg/day)
dist_range: None


# Specific to the background generator BackgroundGen object ###########################################################
interval_threshold: 0.1             # threshold applied in preprocessing the image
stretch: 1                         # stretch factor applied to a Asinh stretch
sigmaclip_sigma: 3.0                 # sigma argument of SigmaClip call
sigmaclip_maxiters: 10               # maxiters argument of SigmaClip call
detect_threshold_nsigma: 2.0         # nsigma argument of detect_threshold call
detect_sources_npixels: 10           # npixels argument of detect_sources call
circular_footprint_radius: 10        # radius argument of circular_footprin call
sigma_clipped_stats_sigma: 3.0       # sigma argument of sigma_clipped_stats call
sigma_cutoff_bottom: 3.0             # number of sigma to cut image below from mean background
sigma_cutoff_top: 5                # number of sigma to cut image above from mean background


# Specific to signal generation SignalGen object ######################################################################

# points of the cubic splines to be fit (all phase angles in degrees)
alphas_phi_12: [0, 7.5, 30, 60, 90, 120, 150, 180]                                                                               # the phase angles of points along spline fits
phi_1_values: [1, 7.5e-1, 3.3486016e-1, 1.3410560e-1, 5.1104756e-2, 2.1465687e-2, 3.6396989e-3, 0]                               # values of phase function
phi_2_values: [1, 9.25e-1, 6.2884169e-1, 3.1755495e-1, 1.2716367e-1, 2.2373903e-2, 1.6505689e-4, 0]                              # for phi_2
alphas_phi_3: [0, 0.3, 1, 2, 4, 8, 12, 20, 30, 60, 90, 180]                                                                      # phase angles of spline points for phi_3
phi_3_values: [1, 8.3381185e-1, 5.7735424e-1, 4.2144772e-1, 2.3174230e-1, 1.0348178e-1, 6.1733473e-2, 1.6107006e-2, 0, 0, 0, 0]  # for phi_3
phi_1_derivative_initial: -1.909859317102744029226605160470172344413515748885477384972008128                                     # -6/pi derivative condition at beginning of spline for phi_1
phi_1_derivative_end: -9.1328612e-2                                                                                              # derivative condition at end of spline for phi_1
phi_2_derivative_initial: -0.572957795130823208767981548141051703324054724665643215491602438                                     # -9 / (5 * np.pi) derivative condition at beginning of spline for phi_2
phi_2_derivative_end: -8.6573138e-8                                                                                              # derivative condition at end of spline for phi_2
phi_3_derivative_initial: -1.0630097e-1                                                                                          # derivative condition at beginning of spline for phi_3
phi_3_derivative_end: 0                                                                                                          # derivative condition at end of spline for phi_3
num_sigmas: 3                                                                                                                    # number of sigmas to increase the aperture size by, background flux calculations

signal_crop_threshold: 5  # this number multiplies sig_g to determine the size of the array that will contain the streak in each frame

##### Imagegen.py specific arguments###################################################################################
number_of_trys: 100
current_set: None



# Specific to the TestSetGen object ##############################################################################
# the values of the quantities in the following lists will be used to permute every single combination in order
# to generate a test set which only varies one quantity at a time
########### for set 1 ##############################
h: [20, 25, 30, 35]  # absolute magnitudes, because the SNR is being varied directly, this quantity is irrelevant
r_oa: [0.01, 0.8]  # observer asteroid distance, because the SNR is being varied directly, this quantity is irrelevant
r_sa: [1, 1.8]  # sun asteroid distance, because the SNR is being varied directly, this quantity is irrelevant
alpha: [0]  # phase angle, because the SNR is being varied directly, this quantity is irrelevant
g_12: [0.47]  # phase constant, because the SNR is being varied directly, this quantity is irrelevant
omega: [0, 500, 2000, 10000]  # angular motion
theta: [0, 20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240, 260, 280, 300, 320, 340]  # orientation of asteroid
sigma: [1, 2, 3, 4]  # thickness of asteroid streak
expected_snr: [1,10, 30, 100]  # SNR of streak on image
original_image: '25.fit'  # image to be used for testing, should be in test folder
crop_start: [405, 186]  # where this image will be cropped to make the sub image
center_x: 112  # where the asteroid will initially be place
center_y: 112

########## for set 2 #############################
num_samples_per_bin: 1
num_bins: 3
min_omega: 0
max_omega: 2500
min_apparent_magnitude: 15
max_apparent_magnitude: 20
min_sigma_g: 2
max_sigma_g: 2